version: "3.3"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/conf/dynamic_conf.yml"  
      - "--providers.file.watch=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=duckdns"
      # Debug
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=rogermm@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"        
    ports:
      - "443:443"
      - "8080:8080"
    env_file:
      - env-duckdns.sh
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./conf:/conf"   
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.rule=Host(`world-dashboard.duckdns.org`)&&PathPrefix(`/traefik`, `/api`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"        
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"

      # stripprefix for dashboard
      - "traefik.http.routers.traefik.middlewares=basic-auth@file,mystrip"
      - "traefik.http.middlewares.mystrip.stripprefix.prefixes=/traefik"

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Sao_Paulo
      - SUBDOMAINS=world-airflow,world-zeppelin,world-dashboard,world-pihole,world-jupyter
      - LOG_FILE=true #optional
    env_file:
      - env-duckdns.sh
    restart: unless-stopped

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)&&Host(`world-dashboard.duckdns.org`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.middlewares=basic-auth@file"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    restart: unless-stopped
      
  yacht:
    image: "selfhostedpro/yacht"
    container_name: "yacht"
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /compose:/compose  
    environment:
      - PUID=0
      - PGID=0
      - COMPOSE_DIR=/compose
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yacht.tls=true"
      - "traefik.http.routers.yacht.rule=Host(`world-pihole.duckdns.org`)"
      - "traefik.http.routers.yacht.entrypoints=websecure"
      - "traefik.http.routers.yacht.middlewares=basic-auth@file"
      - "traefik.http.routers.yacht.tls.certresolver=myresolver"
    restart: unless-stopped

  # https://gitlab.torproject.org/tpo/anti-censorship/docker-snowflake-proxy
  snowflake-proxy:
    network_mode: host
    image: thetorproject/snowflake-proxy:latest
    container_name: snowflake-proxy
    restart: unless-stopped
    command: [ "-ephemeral-ports-range", "30000:60000" ]

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    network_mode: "host"
    environment:
      TZ: 'America/Sao_Paulo'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.12.0
    container_name: "prometheus"
    # volumes:
    #   - ./prometheus/config/:/etc/prometheus/
    #   - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.route-prefix=/prometheus'
      - '--web.external-url=http://world-dashboard.duckdns.org/prometheus'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus`)&&Host(`world-dashboard.duckdns.org`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.middlewares=basic-auth@file"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    links:
      - prometheus
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/etc/grafana/:/etc/grafana/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)&&Host(`world-dashboard.duckdns.org`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
        #- "traefik.http.routers.grafana.middlewares=basic-auth@file"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
    restart: unless-stopped

volumes:
  yacht:
  grafana:
